trigger:
  - main

pool: Infra-Self-hosted

stages:
  - stage: Scan
    displayName: TerraforSecurityScan
    jobs:
      - job: ScanJob
        steps: 
         - script: |
             echo "Running TFLint..."
             tflint
           displayName: "Run TFLint"
         - script: |
             echo "Running tfsec..."
             tfsec .
           displayName: "Run tfsec"
         - script: |
             echo "Running Checkov..."
             checkov -d .
           displayName: "Run Checkov"  

         - script: |
             python3 -m pip install --upgrade checkov
             checkov -d .
           displayName: 'Checkov IaC Scan'  

  - stage: ContinousIntegration
    displayName: ContinousIntegration
    jobs:
      - job: TerraformJob
        displayName: InitValidatePlan
        steps: 
        - task: TerraformInstaller@1
          displayName: TerraformInstaller
          inputs:
            terraformVersion: 'latest'

        - script: |
            echo "========================================="
            echo "Current System.DefaultWorkingDirectory is:"
            echo "$(System.DefaultWorkingDirectory)"
            echo "========================================="
            echo "Listing all files in this directory:"
            dir
            echo "========================================="
          displayName: 'DEBUG: Find my files'    
        - task: TerraformTask@5
          displayName: TerraformInitialization
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'Service-Connection'
            backendAzureRmStorageAccountName: 'storagevistara999'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'backendtfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'Service-Connection'
        - task: TerraformTask@5
          displayName: TerraformValidation
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Service-Connection'
          
  - stage: ManualValidation
    displayName: ManualValidation       
    
    jobs:
      - job: ManualValidation
        pool: server
        steps:
        - task: ManualValidation@0
          inputs:
            notifyUsers: 'saurabh.shrivastwa87@gmail.com'
            approvers: 'Saurabh Shrivastwa'
        
             
  - stage: ContinousDelivery
    displayName: ContinousDelivery
     
    jobs: 
      - job: TerraformInit
        steps: 
        - task: TerraformTask@5
          displayName: TerraformInitialization
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'Service-Connection'
            backendAzureRmStorageAccountName: 'storagevistara999'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'backendtfstate'       
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Service-Connection'




       
      




