trigger:
  - main

pool: Infra-Self-hosted

stages: 
  - stage: TerraformStage
    displayName: ContinousIntegration

    jobs:
      - job: TerraformJob
        displayName: InitValidatePlan
        steps: 
        - powershell: |
            Write-Host "Default Directory: $(System.DefaultWorkingDirectory)"
            Write-Host "Build Sources Directory: $(Build.SourcesDirectory)"
            Get-ChildItem "$(System.DefaultWorkingDirectory)"
          displayName: Check Workspace

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Project-Infra-Automation'
            backendServiceArm: 'Service-Connection'
            backendAzureRmStorageAccountName: 'storagevistara999'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'backendtfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Project-Infra-Automation'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Project-Infra-Automation'
       
      




